### ISSUE TITLE
Including an image in description results in error

### ISSUE THREAD

**Issue by chillsauce** [atticlab/eos-wps-front#20]
If you include an image in the description using the included insert image feature in the formatting options, you get an "overview can't be empty" error when you attempt to submit the description. 

![Screen Shot 2019-12-30 at 4 22 47 PM](https://user-images.githubusercontent.com/37008057/71601324-f48c3a80-2b20-11ea-96fd-f16c88a6aa3d.png)

**Comment by StanCheb** [comment]
The error appears because an added image is encoded to the base64 format which is a too long string for our validation rules.

We've removed the option of adding images to a description as we've decided not to store any images on chain (for the same reason we changed an image editor for the first step in the proposal creator to an image link earlier).
